"""added 'wins' and 'losses' column for 'User' model

Revision ID: d739996bc785
Revises: 249cdde0a880
Create Date: 2021-08-02 22:37:13.478930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd739996bc785'
down_revision = '249cdde0a880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('losses', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('wins', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wins')
    op.drop_column('users', 'losses')
    # ### end Alembic commands ###
