"""added player played card column for War model

Revision ID: 85b5aad4a6e3
Revises: 7ec358cd55ca
Create Date: 2021-07-29 18:06:20.030637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b5aad4a6e3'
down_revision = '7ec358cd55ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wars', sa.Column('player1_played_card', sa.String(), nullable=True))
    op.add_column('wars', sa.Column('player2_played_card', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wars', 'player2_played_card')
    op.drop_column('wars', 'player1_played_card')
    # ### end Alembic commands ###
