"""updated card model to include image column

Revision ID: 7ec358cd55ca
Revises: baf0fa668cde
Create Date: 2021-07-29 17:36:06.120849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec358cd55ca'
down_revision = 'baf0fa668cde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'image')
    # ### end Alembic commands ###
